apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lister
  name: lister
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lister
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lister
    spec:
      containers:
      - image: shengping/use_client:0.0.1
        name: use-client-mk8ch
        resources: {}
status: {}
